{
  try {
    fc.rename(src,dst);
    if (!renameShouldSucceed)     Assert.fail("rename should have thrown exception");
  }
 catch (  Exception e) {
    if (renameShouldSucceed)     Assert.fail("rename should have suceeded, but threw exception");
  }
  Assert.assertEquals("Source exists",srcExists,fc.exists(src));
  Assert.assertEquals("Destination exists",dstExists,fc.exists(dst));
}
