{
  try {
    return doWorkInternal(tool);
  }
 catch (  Exception e) {
    tool.printError(e.getMessage());
  }
  return -1;
}
