{
  try {
    new CallQueueManager<ExceptionFakeCall>(exceptionQueueClass,false,10,"",null);
    fail();
  }
 catch (  RuntimeException re) {
    assertTrue(re.getCause() instanceof IllegalArgumentException);
    assertEquals("Exception caused by constructor.!!",re.getCause().getMessage());
  }
}
