{
  try {
    assertExceptionContains("Expected",new Exception("(actual)"));
  }
 catch (  AssertionError e) {
    String s=e.toString();
    if (!s.contains(E_UNEXPECTED_EXCEPTION) || !s.contains("(actual)")) {
      throw e;
    }
    if (e.getCause() == null) {
      throw new AssertionError("No nested cause in assertion",e);
    }
  }
}
